### PR TITLE
Add map panel

### PR DESCRIPTION
**Pull request by yusukefs**
## What?

マップ表示パネルを追加

## Why?

マップを表示したい

## Screenshot or video

https://user-images.githubusercontent.com/13210107/146302614-3c983e0a-a97c-4b90-ae58-25110bc341f9.mov

### CODE REVIEW

**Comment by hdl-service** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/dataware-tools/webviz/pull/5#" title="Author self-approved">yusukefs</a>*


The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=dataware-tools%2Fwebviz).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/dataware-tools/webviz/blob/dataware-tools/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by yusukefs** [comment]
現在位置の表示と合わせて動かす機能は別PRで追加します

**Review by WatanabeToshimitsu — APPROVED** [review]
LGTM!

**Comment by hdl-service** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/dataware-tools/webviz/pull/5#pullrequestreview-833666668" title="Approved">WatanabeToshimitsu</a>*, *<a href="https://github.com/dataware-tools/webviz/pull/5#" title="Author self-approved">yusukefs</a>*


The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=dataware-tools%2Fwebviz).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/dataware-tools/webviz/blob/dataware-tools/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
